version: "3"
services:
  chatgpt-telegram-bot:
    container_name: chatgpt-telegram-bot
    image: ghcr.io/leafduo/chatgpt-telegram-bot:latest
    restart: always
    environment:
      - OPENAI_API_KEY=<your_openai_api_key>
      - TELEGRAM_APITOKEN=<your_telegram_bot_token>
      # optional, default is empty. Only allow these users to use the bot. Empty means allow all users.
      - ALLOWED_TELEGRAM_ID=<your_telegram_id>,<your_friend_telegram_id>
      # optional, default is 1.0. Higher temperature means more random responses.
      # See https://platform.openai.com/docs/api-reference/chat/create#chat/create-temperature
      - MODEL_TEMPERATURE=1.0
      # See README.md for more options